version: '3.1'

services:

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - "candr-db:/var/lib/postgresql/data"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"

volumes:
  candr-db: