version: '3.1'

services:

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - "candr-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ".:/app"

volumes:
  candr-db: